name: Deploy to registries

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

jobs:
  build-and-deploy:
    name: Build and deploy NPM package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Configure node for NPM as registry
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Prepare packages
        run: pnpm prepare

      - name: Set registry
        run: "echo \"//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}\" >> .npmrc"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Publish packages on NPM
        run: pnpm publish -r --no-git-checks
